# Generated by Django 4.2.1 on 2023-05-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(max_length=200)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_category', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=200)),
                ('product_image_url', models.URLField(blank=True)),
                ('product_price', models.IntegerField()),
            ],
        ),
    ]
